name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test
